### ISSUE TITLE
tengine-2.2.2不支持软重启

### ISSUE THREAD

**Issue by tianyang433** [intel/asynch_mode_nginx#1]
我用的是tengine-2.2.2版本，使用的过程中发现nginx -s reload 时候会报错，nginx报错信息如下
"[error] icp_sal_userStart() - : icp_adf_userProcessToStart failed" 
请问有没有支持reload的patch？

**Comment by tianyang433** [comment]
You know my English is very bad, so you also made a Chinese answer, thanks again to Changzheng's elaborate answer.

**Comment by tianyang433** [comment]
tengine-2.2.2把workprocess 调小到16是可以reload，v0.3.3的release中新引入的功能我还没有测试，你们有patch提供吗？我想在tengine把这个新功能的path打上测试一下。

**Comment by weicz11** [comment]
In Aysnc Mode Nginx repo
$ git diff v0.3.1 v0.3.3 > for_tengine.patch

In Tengine repo
$ git checkout tengine-2.2.2
$ patch -p1 <for_tengine.patch

这里有几个文件tengine没有，一直默认回车继续直至patch过程完成
得到以下冲突文件
       auto/make.rej
       auto/modules.rej
       auto/sources.rej
       modules/nginx_qat_module/
       src/core/nginx.c.rej
       src/core/ngx_connection.c.rej
       src/core/ngx_connection.h.rej
       src/engine/
       src/event/ngx_event_openssl.c.rej
       src/http/ngx_http_request.c.rej
       src/os/unix/ngx_daemon.c.rej
       src/os/unix/ngx_os.h.rej
       src/os/unix/ngx_process_cycle.c.rej
大部分都是些小冲突，找到对应的代码位置手动修改进去就好，唯一改动比较大的是src/event/ngx_event_openssl.c，因为我们nginx的OpenSSL模块进行了大量改写，建议你可以直接用async_mode_nginx中的src/event/ngx_event_openssl.c文件替换掉tengine相应的文件。
时间仓促我没有做验证，你可以自己试一下。
然后就参考我们README.md中的配置（不需要再配置openssl.cnf文件）
例如：
load_module modules/ngx_ssl_engine_qat_module.so;
ssl_engine {
      use_engine qat;
      default_algorithms RSA;
      qat_engine {
              qat_offload_mode async;
              qat_notify_mode poll;
              qat_poll_mode heuristic;
              qat_shutting_down_release on;
     }
}
用来配置启用QAT（注意load_modules的配置要放置在event配置块前）
