### ISSUE TITLE
Triggering async event timeouts for slow connections

### ISSUE THREAD

**Issue by pracj3am** [intel/asynch_mode_nginx#12]
An async event time out is set up if `SSL_get_error` returns `SSL_ERROR_WANT_ASYNC`:
```c
ngx_add_timer(c->async, NGX_ASYNC_EVENT_TIMEOUT);
```
But the timer is never deleted.

So it happens, if for example nginx is waiting for data to be read from connection for more than `NGX_ASYNC_EVENT_TIMEOUT` (10 seconds), the timer finishes and `c->async->timedout` is set to 1.

I think that the timer should be deleted when an async event is triggered. Which means that
```c
    if (aev->timer_set) {
        ngx_del_timer(aev);
    }
```
should be in every`ngx_ssl_*_async_handler`. 

Tested with `NGX_ASYNC_EVENT_TIMEOUT` 1000 and it indeed fixes the problem.

One more question. Is there any particular reason that async timeout is chosen to be 10 seconds?

**Comment by daweiq** [comment]
We set NGX_ASYNC_EVENT_TIMEOUT = 10s to wait for the finish of async job in QAT engine. 
It seems when set NGX_ASYNC_EVENT_TIMEOUT  to 1s, the async job never finished or the async job status never set back. 
We have reproduce this issue in lab and will follow this issue.

**Comment by daweiq** [comment]
Fixed in https://github.com/intel/asynch_mode_nginx/issues/11
