### ISSUE TITLE
should I delete openssl.cnf?

### ISSUE THREAD

**Issue by jiangzhuti** [intel/asynch_mode_nginx#17]
>  this kind of configuration in openssl.conf will not be effective for Nginx

so should i delete it? if i keep it, then it's failed to start nginx:

>  nginx: [emerg] QAT Engine failed: ENABLE_EXTERNAL_POLLING
>  nginx: [emerg] ssl engine send ctrl failed
>  nginx: [emerg] ssl engine set failed

**Comment by daweiq** [comment]
Yes,  please  delete the openssl.cnf file if you follow the README and enabled the polling config in nginx.conf.
Because the configuration in openssl.cnf might have conflict with polling config in nginx.conf.
