### ISSUE TITLE
死循环bug

### ISSUE THREAD

**Issue by jiangzhuti** [intel/asynch_mode_nginx#18]
现在有几个业务，nginx启动后几分钟就会有进程100%cpu占满，gdb attach看了一下是这样子：
![ngx1](https://user-images.githubusercontent.com/3127813/55769693-39180780-5ab4-11e9-8779-201fdc3dd3b7.png)

nginx.conf：
load_module modules/ngx_ssl_engine_qat_module.so;
ssl_engine {
    use_engine qat;
    default_algorithms RSA;
    qat_engine {
        qat_offload_mode async;
	qat_notify_mode poll;
	qat_poll_mode external;
	qat_shutting_down_release on; 
    }   
}

其中的poll mode 改成heuristic一样有问题

qat engine相关代码：
![ngx2](https://user-images.githubusercontent.com/3127813/55769714-5056f500-5ab4-11e9-8d82-bf6142e5f25c.png)
应该是这个循环一直出不来

相同方案在另一个类似业务里却没出问题，两者代码完全相同，区别是出问题的业务会跑一部分lua代码，用的是`LuaJIT-2.0.5`和`lua-nginx-module-0.9.20`，不出问题的业务不会跑到lua代码。lua主要做了计算md5和重定向。

**Comment by jiangzhuti** [comment]
怎样继续排查问题原因？

**Comment by daweiq** [comment]
如果问题比较急，需要现场Support，建议先联系Intel AE。
Github上只是为了讨论通用技术问题。
