### ISSUE TITLE
Problem with Openssl_1.1.1

### ISSUE THREAD

**Issue by smesgary** [intel/asynch_mode_nginx#19]
Hi
I want to use asynch_mode_nginx with openssl_1.1.1 and i get this error in nginx error log:

 SSL_get_error : 10

Do you have any plan to support Openssl_1.1.1?

I want to use openssl_1.1.1 because of TLS1.3

Thanks

**Comment by daweiq** [comment]
I which use case you see this error?

**Comment by smesgary** [comment]
what do you mean by usecase? i use async for call handshake asynchronous , but in openssl1.1.1 i get this error.

Do you ever test with openssl 1.1.1 or higher?

**Comment by iaMartin8820** [comment]
openssl 1.1.1 was works.

**Comment by daweiq** [comment]
Yes, we have been tested with OpenSSL 1.1.1a for TLS-1.2 handshake test, ti works well. 
Do you change the nginx.conf to use TLS1.3? 
If yes, would you please share the conf for reproduce?

**Comment by smesgary** [comment]
Thanks for your answers. It works,  it was my miss-configuration.

I have another question. Intel provided a patch for Async about two years ago and then this github project created.
That async patch for nginx was independent from QAT technology, but this github project is not.
Is there any solution to use this project independent from QAT just like that patches? just for make nginx async in ssl handshakes.

**Comment by daweiq** [comment]
You try to load the dasync module and enable dasync engine which will offload the requests to dymmy async engine in OpenSSL and enable async job processed by CPU. 

```
load_module modules/dasync_module.so;
...
ssl_engine {
        use_engine dasync;
        default_algorithms RSA,EC,DH,PKEY_CRYPTO;
...
}
```
