### ISSUE TITLE
Query regarding QAT engine default algorithm

### ISSUE THREAD

**Issue by premtata** [intel/asynch_mode_nginx#25]
This is not an issue ,but query regarding the behavior of nginx. If the default algorithm set to RSA and if the request connection cipher is some other type  elliptical curve ,what will happen to the request?. Will be dropped at nginx level or what would be the behavior?

**Comment by daweiq** [comment]
Do you mean the "default_algorithms" setup in SSL_Engine section? 
If yes, only the RSA handshake operation will be offload to QAT.
Any-other type of requests, like EC,  will be processed by CPU in SW manner as it is in official Nginx version.
