### ISSUE TITLE
module for nginx-plus

### ISSUE THREAD

**Issue by mironnik** [intel/asynch_mode_nginx#26]
Is it possible build module for nginx plus?

**Comment by daweiq** [comment]
Although, we have not tested it. 
But yes, it should work on both Nginx plus and Nginx  as they all support dynamic module.

Please be aware that to support the external/heuristical polling, we changed the nginx_connection.c, nginx_epoll_module.c to enable async-event. 
You can diff the async-Nginx 0.3.7 package against the official 1.14.2 version to get the detail information.
