### ISSUE TITLE
what kind of Driver config do i need to run nginx?

### ISSUE THREAD

**Issue by zengjinji** [intel/asynch_mode_nginx#28]
i install all Software Requirements, then Run Nginx official test failed, maybe i have not correct Driver config files?

according to Software Requirements. it need QAT engine and QATzip. but both of them are need correct Driver config files to work.

when i install QAT engine and copy QAT engine's Driver config files(/QAT_Engine/qat/config/c6xx/multi_process_optimized) to /etc, run command ./openssl engine -t -c -vvvv qat is available.

when i install QATzip and copy QATzip's Driver config files(/QATzip/config_file/c6xx/multiple_process_opt/*) to /etc,  command cd $QZ_ROOT/test/performance_tests and ./run_perf_test.sh work well
, but run command ./openssl engine -t -c -vvvv qat is unavailable.

It seems according to readme install, I can only make one of them work properly. so what kind of Driver config do i need to run nginx?

my environment
```
centos7
3.10.0-693.el7.x86_64

#lsmod | fgrep qa
qat_c62x               17889  0 
intel_qat             212930  2 usdm_drv,qat_c62x
authenc                17776  1 intel_qat
uio                    19259  1 intel_qat
qat_contig_mem         13414  0 
```

when i run ./nginx-test.sh qat or ./nginx-test.sh dasync, both failed and failed log are
```
./h2.t                               (Wstat: 6400 Tests: 143 Failed: 25)
  Failed tests:  30-31, 43-44, 46, 53-55, 58, 60-61, 64-72
                80-81, 83, 90, 116
  Non-zero exit status: 25
./h2_fastcgi_request_buffering.t     (Wstat: 3072 Tests: 50 Failed: 12)
  Failed tests:  4, 9, 13, 17, 20, 24, 29, 33, 37, 41, 45
                48
  Non-zero exit status: 12
./h2_headers.t                       (Wstat: 65280 Tests: 65 Failed: 43)
  Failed tests:  1-18, 20, 23, 25, 27, 39-55, 57-60
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 94 tests but ran 65.
./h2_limit_conn.t                    (Wstat: 512 Tests: 6 Failed: 2)
  Failed tests:  1, 3
  Non-zero exit status: 2
./h2_limit_req.t                     (Wstat: 1280 Tests: 9 Failed: 5)
  Failed tests:  1-5
  Non-zero exit status: 5
./h2_proxy_cache.t                   (Wstat: 512 Tests: 14 Failed: 2)
  Failed tests:  1, 4
  Non-zero exit status: 2
./h2_proxy_protocol.t                (Wstat: 256 Tests: 6 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
./h2_proxy_request_buffering.t       (Wstat: 3072 Tests: 51 Failed: 12)
  Failed tests:  4, 8, 12, 16, 20, 25, 28, 32, 37, 41, 45
                48
  Non-zero exit status: 12
./h2_proxy_request_buffering_ssl.t   (Wstat: 2560 Tests: 42 Failed: 10)
  Failed tests:  4, 9, 13, 17, 20, 24, 29, 33, 37, 40
  Non-zero exit status: 10
./h2_proxy_ssl.t                     (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
./h2_request_body.t                  (Wstat: 9728 Tests: 44 Failed: 38)
  Failed tests:  1-4, 6-14, 17, 19-42
  Non-zero exit status: 38
./h2_request_body_preread.t          (Wstat: 512 Tests: 10 Failed: 2)
  Failed tests:  1, 8
  Non-zero exit status: 2
./h2_server_tokens.t                 (Wstat: 1536 Tests: 11 Failed: 6)
  Failed tests:  1-2, 4-5, 7-8
  Non-zero exit status: 6
./h2_ssl_verify_client.t             (Wstat: 768 Tests: 5 Failed: 3)
  Failed tests:  1-3
  Non-zero exit status: 3
./h2_variables.t                     (Wstat: 256 Tests: 6 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
./mail_imap_ssl.t                    (Wstat: 256 Tests: 14 Failed: 1)
  Failed test:  10
  Non-zero exit status: 1
./proxy_ssi_body.t                   (Wstat: 0 Tests: 3 Failed: 0)
  TODO passed:   1
./ssl.t                              (Wstat: 1024 Tests: 12 Failed: 8)
  Failed tests:  3-10
  Non-zero exit status: 4
  Parse errors: Bad plan.  You planned 20 tests but ran 12.
```

**Comment by zhangp8x** [comment]
@zengjinji 
Good news, our 0.3.9 had released, you can try the newest version.
Make sure you have more than one Dc and Cy, for example:
##############################################
1.	User Process Instance Section
##############################################
[SHIM]
NumberCyInstances = 1
NumberDcInstances = 1
NumProcesses = 1
LimitDevAccess = 0
1.	Crypto - User instance #0
Cy0Name = "SSL0"
Cy0IsPolled = 1
2.	List of core affinities
Cy0CoreAffinity = 1
1.	Data Compression - User instance #0
Dc0Name = "Dc0"
Dc0IsPolled = 1
2.	List of core affinities
Dc0CoreAffinity = 1

**Comment by zengjinji** [comment]
@zhangp8x  Thank you for your help，after modif my driver config，it work well and all nginx-tests pass
