### ISSUE TITLE
QAT Engine failed: ENABLE_HEURISTIC_POLLING

### ISSUE THREAD

**Issue by onioner** [intel/asynch_mode_nginx#3]
Hello Team,

I have successfully installed the services according to the document, and there is no problem in the nginx configuration test, but I can't start it successfully. The wrong information is as follows:
nginx: [emerg] QAT Engine failed: ENABLE_HEURISTIC_POLLING
nginx: [emerg] ssl engine send ctrl failed
nginx: [emerg] ssl engine set failed

This is the version of my services:
nginx: openresty-1.13.6.2
openssl: 1.1.0g
QAT driver: QAT1.7.Upstream.L.1.0.3_42
QAT engine: 0.5.34

Thanks in advance!

**Comment by weicz11** [comment]
As REAMDE.md figured out "This mode is only available when using QAT engine v0.5.35 or later.", so please upgrade your QAT engine version.
