### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by manjeetbhatia** [intel/asynch_mode_nginx#30]
is there any docker image for this that could be used in kubernetes?

**Comment by daweiq** [comment]
Sorry, we don't have the docker image yet. 
While, there is a docker image template under developmenting in github.
https://github.com/OpenVisualCloud/Dockerfiles/blob/master/template/nginx-qat.m4
You can try starting from there. 

Besides, the async-Nginx is designed to accelerate Nginx with QAT. 
So, you will need to enable QAT driver in your docker image as well.
Here's the document for it:
https://01.org/sites/default/files/downloads/intelr-quickassist-technology/337020-001qatwcontaineranddocker.pdf

**Comment by daweiq** [comment]
The docker image for QAT is now available on OpenVisualCould project. 
https://github.com/OpenVisualCloud/Dockerfiles/tree/master/QAT 
You can have a try on it.
