### ISSUE TITLE
使用了QAT加速卡似乎没有效果

### ISSUE THREAD

**Issue by liuzh-sa** [intel/asynch_mode_nginx#34]
CPU使用率都是 
![image](https://user-images.githubusercontent.com/61768861/76075169-7d1ecf80-5fd7-11ea-9bc8-0d768b9019cb.png)
QPS都是7000+
![image](https://user-images.githubusercontent.com/61768861/76075275-adff0480-5fd7-11ea-8cb5-6909e8ba862b.png)
但是这个计数器的数值是在变化的 /sys/kernel/debug/qat_dh895xcc_0000\:1c\:00.0/fw_counters
下面是我的nginx配置：
worker_processes  16;

load_module modules/ngx_http_qatzip_filter_module.so;
load_module modules/ngx_ssl_engine_qat_module.so;

events {
        use epoll;
        worker_connections 65535;
}

# Enable QAT engine in heretic mode.
ssl_engine {
    use_engine qat;
    default_algorithms ALL;
    #default_algorithms RSA,EC,DH,DSA;
    qat_engine {
        qat_offload_mode async;
        qat_notify_mode poll;
        qat_poll_mode heuristic;
        qat_sw_fallback on;
    }
}

http {
    gzip on;
    gzip_min_length     128;
    gzip_comp_level     1;
    gzip_types  text/css text/javascript text/xml text/plain text/x-component application/javascript application/json application/xml application/rss+xml font/truetype font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary            on;
    gzip_disable        "msie6";
    gzip_http_version   1.0;

    qatzip_sw failover;
    qatzip_min_length 128;
    qatzip_comp_level 1;
    qatzip_buffers 16 8k;
    qatzip_types text/css text/javascript text/xml text/plain text/x-component application/javascript application/json application/xml application/rss+xml font/truetype font/opentype application/vnd.ms-fontobject image/svg+xml application/octet-stream image/jpeg;
    qatzip_chunk_size   64k;
    qatzip_stream_size  256k;
    qatzip_sw_threshold 256;
   
    keepalive_timeout 0;
    keepalive_requests 0;
    sendfile on;
    tcp_nopush     on;
    tcp_nodelay on;
    
    log_format gdttest '{"time_local":"$time_iso8601",'
                           '"client":"$remote_addr",'
                           '"url":"$uri",'
                           '"status":$status,'
                           '"domain":"$host",'
                           '"upstream_addr":"$upstream_addr",'
                           '"upstream_connect_time":"$upstream_connect_time",'
                           '"upstream_header_time":"$upstream_header_time",'
                           '"upstream_response_time":"$upstream_response_time",'
                           '"request_time":"$request_time"'
                '}';
 
    vhost_traffic_status_zone shared:vhost_traffic_status:32m;
    vhost_traffic_status_filter_by_host on;
    vhost_traffic_status_filter_max_node 16 uris client::ports;

    include vhosts/*.conf;

}
server {
        #If QAT Engine enabled,  `asynch` need to add to `listen` directive or just add `ssl_asynch  on;` to the context.
        listen       443 backlog=65535 ssl asynch;
        server_name  ssltest.test.com;
        access_log logs/ssl.log gdttest;

        ssl_protocols       TLSv1.2;
        ssl_certificate ssl/test.com.crt;
        ssl_certificate_key ssl/test.com.key;

        location / {
        proxy_pass http://os_test;
        proxy_connect_timeout 10s;
        proxy_read_timeout 10s;
        proxy_send_timeout 10s;
        proxy_set_header X-Http-scheme https;
        proxy_set_header u-se-real-ip $remote_addr;
        proxy_set_header    X-Real-IP       $remote_addr;
        proxy_set_header    Host    $host:$server_port;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
       }

    }
nginx还伴随一些报错：
[error] cpaDcGetInstances() - : Invalid API Param - numInstances is 0
Error in cpaDcGetInstances status = -4
g_process.qz_init_status = QZ_NO_HW
[error] cpaDcGetInstances() - : Invalid API Param - numInstances is 0
Error in cpaDcGetInstances status = -4
g_process.qz_init_status = QZ_NO_HW

**Comment by yongchengmiao** [comment]
Hi @liuzh-sa 

关于error问题
麻烦给一下你构筑环境相关的软件版本：
- QAT driver version
- QAT Engine version and configure command used in the build
- OpenSSL version and build commands
- Async Nginx version and build commands

关于 QPS的问题，
如果可能，你最好能提供一下你Client端/Server端的细节.
是否参考了如下信息进行构筑你的环境。
https://01.org/sites/default/files/downloads/intelr-quickassist-technology/337003-001-intelquickassisttechnologyandopenssl-110.pdf

**Comment by zhangp8x** [comment]
@liuzh-sa
Please check your configuration under /etd/dh895xcc_dev0.conf, one example is:
```
##############################################
# User Process Instance Section
##############################################
[SHIM]
NumberCyInstances = 1
NumberDcInstances = 1
NumProcesses = 32
LimitDevAccess = 0

# Crypto - User instance #0
Cy0Name = "SSL0"
Cy0IsPolled = 1
# List of core affinities
Cy0CoreAffinity = 0

# Data Compression - User instance #0
Dc0Name = "Dc0"
Dc0IsPolled = 1
# List of core affinities
Dc0CoreAffinity = 0
```

**Comment by liuzh-sa** [comment]
> Hi @liuzh-sa
> 
> 关于error问题
> 麻烦给一下你构筑环境相关的软件版本：
> 
> * QAT driver version
> * QAT Engine version and configure command used in the build
> * OpenSSL version and build commands
> * Async Nginx version and build commands
> 
> 关于 QPS的问题，
> 如果可能，你最好能提供一下你Client端/Server端的细节.
> 是否参考了如下信息进行构筑你的环境。
> https://01.org/sites/default/files/downloads/intelr-quickassist-technology/337003-001-intelquickassisttechnologyandopenssl-110.pdf

非常感谢你的回复，我的环境软件版本如下：

- QAT driver version  
   Intel_QAT_Linux_1.7.l.4.5.0-00034
- QAT Engine version and configure command used in the build
   QAT_Engine-0.5.43
   ./configure --with-qat_dir=/usr/local/soft/QAT --with-openssl_dir=/usr/local/soft/openssl-OpenSSL_1_1_1c --with-openssl_install_dir=/usr/local/ssl --enable-upstream_driver --enable-usdm
- OpenSSL version and build commands
   openssl-OpenSSL_1_1_1c
   ./config --prefix=/usr/local/ssl
- Async Nginx version and build commands
   v0.4.0
   ./configure --prefix=/app/nginx --user=root --group=root --with-openssl=/usr/local/ssl \
--with-http_ssl_module --with-http_stub_status_module --with-http_v2_module  \
--with-stream --with-stream_ssl_module  --with-http_gzip_static_module \
--add-module=/app/nginx-module-vts-master --add-module=/usr/local/src/nginx_upstream_check_module-master \
--add-dynamic-module=modules/nginx_qatzip_module \
--add-dynamic-module=modules/nginx_qat_module/ \
--with-pcre-opt='-g -Ofast -fPIC -m64 -march=native -fstack-protector-strong -D_FORTIFY_SOURCE=2' \
--with-zlib-opt='-g -Ofast -fPIC -m64 -march=native -fstack-protector-strong -D_FORTIFY_SOURCE=2' \
--with-cc-opt="-DNGX_SECURE_MEM -I/usr/local/ssl/lib/include -I/usr/local/soft/QATzip-1.0.1/include -Wno-error=deprecated-declarations" \
--with-ld-opt="-Wl,-rpath=/usr/local/ssl/lib -L/usr/local/ssl/lib -L/usr/local/soft/waf_package/QATzip-1.0.1/src -lqatzip -lz -lssl"

https://01.org/sites/default/files/downloads/intelr-quickassist-technology/337003-001-intelquickassisttechnologyandopenssl-110.pdf 这个文档看过，并且按照里面的方法对openssl做了测试，性能和下图差不多。
![image](https://user-images.githubusercontent.com/61768861/76194832-f3167700-6221-11ea-8c10-97d4179d69ef.png)

**Comment by zhangp8x** [comment]
@liuzh-sa 
What is your current issue now?
You had load modules/ngx_http_qatzip_filter_module.so, so by default, the QATzip is enabled by default. you need Dc instance, please check your driver configuration file.

If you do not want to enable QATzip, you should remove 
`load_module modules/ngx_http_qatzip_filter_module.so;`

**Comment by liuzh-sa** [comment]
> @liuzh-sa
> What is your current issue now?
> You had load modules/ngx_http_qatzip_filter_module.so, so by default, the QATzip is enabled by default. you need Dc instance, please check your driver configuration file.
> 
> If you do not want to enable QATzip, you should remove
> `load_module modules/ngx_http_qatzip_filter_module.so;`

不好意思，英文不太好就不回复中式英语了。
我现在的问题是，从我的压测结果来看，CPU使用率并没有下降。

**Comment by zhangp8x** [comment]
@liuzh-sa :
Have you restart your computer? The configuration file can not be effective if you just modify it.
And QATzip should be disabled, if you want a peak performance.

**Comment by liuzh-sa** [comment]
> @liuzh-sa :
> Have you restart your computer? The configuration file can not be effective if you just modify it.
> And QATzip should be disabled, if you want a peak SSL performance.

我没有重启服务器，重启了 qat_service：service qat_service restart. 修改这个配置文件需要重启服务器么？

QATzip 我在nginx配置中注释了，效果还是不行。
![image](https://user-images.githubusercontent.com/61768861/76198441-06791080-6229-11ea-86e7-ff14f8ebe9a3.png)

**Comment by zhangp8x** [comment]
@liuzh-sa :

Do you have any error now? I think we have resolve the Dc instance not enough issue.

**Comment by liuzh-sa** [comment]
> @liuzh-sa :
> 
> Do you have any error now? I think we have resolve the Dc instance not enough issue.

是的，现在没有其它错误了，种种迹象都表明QAT Engine已经安装成功了，可是CPU使用率还是降不下来...

**Comment by yucaox** [comment]
@liuzh-sa 

Hi, 
Here's some knowledge we got, I would like to know if it solve your problem.

## About CPU usage
The CPU usage should be still high when enabled QAT in Nginx, but the CPS should also grown higher.

During our performance testing, the CPU usage is almost 100% when QAT reached best performance.
And generally, the performance result is better than the one without QAT acceleration.

For Nginx, the worker will still process with other requests after sent the crypto offloads to QAT.
Which keeps the Nginx worker busy, also the CPU busy.

## About Performance
According to White Paper(https://01.org/sites/default/files/downloads/intelr-quickassist-technology/337003-001-intelquickassisttechnologyandopenssl-110.pdf),
The best performance should around tens of thousands CPS(Depend on different cipher).

And I noticed your performance result is 7000+ QPS, it's quite a gape.

Which because your performance testing environment setups and commands are different from us.
So, we have the following items may explain the performance gape.

1. The larger file size you request, the less QAT acceleration effect you got.
 Our performance result is based on CPS(Connections Per Second), 
And I noticed your performance result is based on QPS.
I don't know the details you requested in this case, But I think it could be the main reason.

2. For performance testing, the client has some performance requirements.
Otherwise, the Nginx performance won't get to the best.
To our testing environment, we use 2 x 40G fiber optic network and thousand of clients for the test.

3. Make sure each Nginx worker got both DC & CY instance.
I don't think this won't be a main cause, with configuration you used, the QAT instances are enough.

    worker_processes 16;

    NumberCyInstances = 1
    NumberDcInstances = 1
    NumProcesses = 32
    LimitDevAccess = 0

4. The performance result also relay on some other setups.
Which could be hardware diffrence(e.g. CPUs, Memory speed, referring to Appendix A Platform Details in White Paper),
or software diffrence(e.g. Nginx configuration, QAT Driver configuration. But I don't think this won't be a main cause).

**Comment by zhangp8x** [comment]
@liuzh-sa 
No reply for a long time, this issue would be closed later.
If you have any question, please reopen this issue.
