### ISSUE TITLE
QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT

### ISSUE THREAD

**Issue by lizj3624** [intel/asynch_mode_nginx#36]
kernel: 3.10.0-957.21.3.el7.x86_64
qat_driver: qat1.7.l.4.7.0-00006
qat_engine: v0.5.43
qat_zip: v1.0.1
openssl: openssl-1.1.1c
asynch_mode_nginx: v0.4.1

[root@mycentos asynch_mode_nginx]# ./sbin/nginx -V
nginx version: nginx/1.16.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
built with OpenSSL 1.1.1c  28 May 2019
TLS SNI support enabled
configure arguments: --prefix=/export/servers/asynch_mode_nginx --with-http_ssl_module --with-http_stub_status_module --with-http_v2_module --with-stream --with-stream_ssl_module --with-pcre=/export/servers/pcre-8.40 --with-pcre-jit --with-zlib=/export/servers/zlib-1.2.11 --with-pcre-opt='-g -Ofast -fPIC -m64 -march=native -fstack-protector-strong -D_FORTIFY_SOURCE=2' --with-zlib-opt='-g -Ofast -fPIC -m64 -march=native -fstack-protector-strong -D_FORTIFY_SOURCE=2' --add-dynamic-module=modules/nginx_qatzip_module --add-dynamic-module=modules/nginx_qat_module --with-cc-opt=' -fPIC -DNGX_SECURE_MEM -I/export/servers/openssl-1.1.1c/include -I/export/servers/qat/QAT-1.7/QATzip/include -Wno-error=deprecated-declarations' --with-ld-opt='-Wl,-rpath=/export/servers/openssl-1.1.1c/lib -L/export/servers/openssl-1.1.1c/lib -L/export/servers/qat/QAT-1.7/QATzip/src -lqatzip -lz -lssl'
nginx.conf:
...
load_module modules/ngx_ssl_engine_qat_module.so;
load_module modules/ngx_http_qatzip_filter_module.so;

events {
    use epoll;
    worker_connections  102400;
}

ssl_engine {
    use_engine qat;
    default_algorithms ALL;
    qat_engine {
        qat_offload_mode async;
        qat_notify_mode poll;
        qat_poll_mode heuristic;
        qat_heuristic_poll_asym_threshold 48;
        qat_heuristic_poll_sym_threshold 24;
    }
}
....
http {
    gzip  on;
    gzip_http_version   1.0;
    gzip_proxied any;
    qatzip_sw failover;
    qatzip_min_length 128;
    qatzip_comp_level 1;
    qatzip_buffers 16 8k;
    qatzip_types text/css text/javascript text/xml text/plain text/x-component application/javascript application/json application/xml application/rss+xml font/truetype font/opentype application/vnd.ms-fontobject image/svg+xml application/octet-stream image/jpeg;
    qatzip_chunk_size   64k;
    qatzip_stream_size  256k;
    qatzip_sw_threshold 256;
    server {
          ....
    }
}

nginx error log:
2020/06/16 18:59:09 [emerg] 4119#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4120#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4121#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4123#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4122#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4124#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4126#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4125#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4137#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4136#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4135#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4138#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4139#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4140#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4142#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4141#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4132#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4128#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4127#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4130#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:09 [emerg] 4129#0: QAT Engine failed: GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:10 [alert] 4117#0: worker process 4119 exited with fatal code 2 and cannot be respawned
2020/06/16 18:59:10 [alert] 4117#0: worker process 4120 exited with fatal code 2 and cannot be respawned
2020/06/16 18:59:10 [alert] 4117#0: worker process 4121 exited with fatal code 2 and cannot be respawned
2020/06/16 18:59:09 [emerg] 4131#0: QAT Engine failed:  GET_NUM_REQUESTS_IN_FLIGHT
2020/06/16 18:59:10 [alert] 4117#0: worker process 4122 exited with fatal code 2 and cannot be respawned
2020/06/16 18:59:10 [alert] 4117#0: worker process 4123 exited with fatal code 2 and cannot be respawned
2020/06/16 18:59:10 [alert] 4117#0: worker process 4124 exited with fatal code 2 and cannot be respawned
2020/06/16 18:59:10 [alert] 4117#0: worker process 4126 exited with fatal code 2 and cannot be respawned

**Comment by zhangp8x** [comment]
@lizj3624 
According to https://github.com/intel/asynch_mode_nginx/releases/tag/v0.4.1, you must use engine v 0.5.44 and openssl 1.1.1g.
Please have a try.

**Comment by lizj3624** [comment]
update engine to v0.5.44，OpenSSL-1.1.1g，prompt https://github.com/intel/QAT_Engine/issues/146 when build

**Comment by zhangp8x** [comment]
@lizj3624 
I cannot reproduce your issue. But you can try use --disable-qat_hkdf to compile engine, seems it is the feature of hkdf, and at the same time wait engine team's reply.

**Comment by lizj3624** [comment]
my qat driver version is qat1.7.l.4.7.0-00006，not found 'CpaCyKeyGenHKDFOpData', 'CpaCyKeyHKDFCipherSuite' in quickassist/include/lac/cpa_cy_key.h，but lastest version qat1.7.l.4.9.0-00008 found，update qat driver lastest version?

**Comment by zhangp8x** [comment]
Yes, the newest version of driver is needed.

**Comment by zhangp8x** [comment]
No reply for a long time, this issue would be closed later.
If you have any question, please reopen this issue.

**Comment by lizj3624** [comment]
ok,  the issue is fixed
