### ISSUE TITLE
infinite loop，CPU 100%  when use stream SSL module

### ISSUE THREAD

**Issue by lizj3624** [intel/asynch_mode_nginx#38]
asynch_mode_nginx：v0.4.1
Deiver： qat1.7.l.4.9.0-00008
Qat_Engine：v0.5.44
OpenSSL-1.1.1g
QATzip：v1.0.1

cat nginx.conf:

worker_processes    16;
worker_cpu_affinity 01111111111111111000000000000000;
user  root;

error_log  logs/error.log error;

pid        nginx.pid;

load_module modules/ngx_ssl_engine_qat_module.so;
load_module modules/ngx_http_qatzip_filter_module.so;

events {
    use epoll;
    worker_connections  102400;
}

ssl_engine {
    use_engine qat;
    default_algorithms ALL;
    qat_engine {
        qat_offload_mode async;
        qat_notify_mode poll;
        qat_poll_mode heuristic;
        qat_sw_fallback on;
    }
}

stream {
    upstream myngx_stream_ups {
        server 172.28.150.52:8881 weight=1 max_fails=3 fail_timeout=5s;
        server 172.28.150.52:8882 weight=1 max_fails=3 fail_timeout=5s;
    }

    log_format main '$remote_addr [$time_local] '
                 '$protocol $status $bytes_sent $bytes_received '
                 '$session_time "$upstream_addr" '
                 '"$upstream_bytes_sent" "$upstream_bytes_received" "$upstream_connect_time"';
    access_log logs/stream_access.log main  buffer=4k flush=5s;
    server {
        listen 172.28.33.190:6443 ssl asynch reuseport;

        ssl_certificate      cert/jd;
        ssl_certificate_key  cert/jd;

        ssl_protocols  TLSv1.2 TLSv1.3;
        ssl_ciphers  ECDH+AESGCM:AES128+RSA:HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
        ssl_session_cache   shared:STREAM_SSL:300m;
        ssl_session_timeout 24h;

        proxy_pass myngx_stream_ups;
    }

    server {
        listen 172.28.33.190:7443 reuseport;
        proxy_pass myngx_stream_ups;
    }
}
![企业咚咚20200701112152](https://user-images.githubusercontent.com/1217777/86202350-9229fa80-bb94-11ea-8ae7-c4dc7fbc52f3.jpg)
![企业咚咚20200701112215](https://user-images.githubusercontent.com/1217777/86202356-9524eb00-bb94-11ea-964e-91d81015a8e9.jpg)

strace -p 8684
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
.....

**Comment by zhangp8x** [comment]
Please try to update nginx.conf as following to avoid this problem.

`listen 172.28.33.190:6443 ssl asynch reuseport;`
=>
```
listen 172.28.33.190:6443 ssl reuseport;
ssl_asynch on; 
```

**Comment by lizj3624** [comment]
the issue is fixed

**Comment by jazune** [comment]
@zhangp8x ssl_asynch on;  config can handle infinite loop for normal https request, but for proxy request, it not works.
use proxy_ssl_asynch on; also not works.

![image](https://user-images.githubusercontent.com/9442957/148049541-be968ebb-142c-48ca-970c-19dcc25f1ff2.png)
![image](https://user-images.githubusercontent.com/9442957/148049619-e3af9ebe-0fd7-43cc-8c56-f96090f9ce79.png)
![image](https://user-images.githubusercontent.com/9442957/148049661-4d390126-1489-4f4c-8c5c-d2ef0085ec17.png)

**Comment by jazune** [comment]
@Yogaraj-Alamenda Can also help to see this question? Thank you.

**Comment by jazune** [comment]
It seems if qat_poll_mode set to  external or  heuristic, it will have the problem, if qat_poll_mode set to internal, it's ok.

**Comment by yongchengmiao** [comment]
Sorry, the issue of closed status has been ignored.
We will reopen the issue.

**Comment by ShuaiYuan21** [comment]
@jazune Can you update the qat_engine to latest version and test again? I cannot preproduce this issue.

**Comment by jazune** [comment]
@ShuaiYuan21 
I also have this issue with the latest version, and it can be reproduced stably with your asynch_mode_nginx. Reproduction method: 1) qat_poll_mode heuristic; 2) the upstream of nginx is https request.

**Comment by ShuaiYuan21** [comment]
This is a known issue, please use the internal polling mode to avoid this defect.
