### ISSUE TITLE
Some style problem for README

### ISSUE THREAD

**Issue by rainingmaster** [intel/asynch_mode_nginx#43]
1. There are extra spaces in `** Nginx supports setting worker to non-root user, for example:**`, and there is a problem with the alignment of the subsequent paragraphs
2. The title is missing for link 9 https://github.com/intel/asynch_mode_nginx/blob/master/test/performance_bkm/README.md

**Comment by zhangp8x** [comment]
@rainingmaster 

Thank you for your support, the issue would be fixed in next release.
