### ISSUE TITLE
Nginx worker CPU 100%，endless loop

### ISSUE THREAD

**Issue by lizj3624** [intel/asynch_mode_nginx#46]
[Nginx worker CPU 100%，endless loop](https://github.com/intel/QAT_Engine/issues/181)

**Comment by zhangp8x** [comment]
@lizj3624 

Seems you are using old version of nginx, please use the newest version.

We also need nginx.conf, ./nginx -V, and how to reproduce this bug

**Comment by zhangp8x** [comment]
@lizj3624 

No response from user, this issue would be closed in 7 days
