### ISSUE TITLE
Segfault on 'nginx -t' if ssl_session_ticket_key is set but server listens on an invalid IP address.

### ISSUE THREAD

**Issue by anguslee** [intel/asynch_mode_nginx#48]
On release: v0.4.6

To reproduce, replace "xxx" with an non-existant IP in the following http config snippet:
```
http {
    include       mime.types;
    default_type  application/octet-stream;

    ssl_certificate cert/test.crt;
    ssl_certificate_key cert/test.key;
    ssl_session_ticket_key cert/ticket.key;

    server {
        listen       xxx:8443;

        location / {
            root   html;
            index  index.html index.htm;
        }
    }
}
```

Then run `nginx -t`:
```
nginx -t
nginx: the configuration file /opt/nginx-asynch/conf/nginx.conf syntax is ok
nginx: [emerg] bind() to xxx:8443 failed (99: Cannot assign requested address)
Segmentation fault (core dumped)
```

But starting nginx directly would not cause the segmentation fault.

```
nginx
nginx: [emerg] bind() to xxx:8443 failed (99: Cannot assign requested address)
```

The cause is in freeing SSL ctx even if it's not been initialized so I proposed the following fix:

https://github.com/intel/asynch_mode_nginx/pull/49

**Comment by zhangp8x** [comment]
@anguslee We will try to reproduce this issue and give you feedback asap.

**Comment by zhangp8x** [comment]
```
nginx: the configuration file /opt/nginx-asynch/conf/nginx.conf syntax is ok
nginx: [emerg] bind() to xxx:8443 failed (99: Cannot assign requested address)
```

The syntax will never OK in my codes, suppose you have changed your nginx source codes.

BRs

**Comment by anguslee** [comment]
Replace "xxx" with an non-existant IP address, as

```
listen       172.15.18.222:8443;
```

Make sure this IP address is invalid in your environment.

**Comment by zhangp8x** [comment]
```
./sbin/nginx -t
nginx: the configuration file /opt/atf/environments/server/install/nginx-qat/installFor1.10.3/conf/nginx.conf syntax is ok
nginx: [emerg] bind() to 172.15.18.222:443 failed (99: Cannot assign requested address)
nginx: configuration file /opt/atf/environments/server/install/nginx-qat/installFor1.10.3/conf/nginx.conf test failed
```

If address is invalid, `(99: Cannot assign requested address)` , could you please help to show how to handle ip 172.15.18.222? Is it bind to a NIC?

**Comment by anguslee** [comment]
It's not necessary to handle this IP. This segfault appears only when you assign an invalid IP address and set the `ssl_session_ticket_key` property.

**Comment by zhangp8x** [comment]
Got you, I will continue to try to reproduce this issue.

But could you please help to verify if the official nginx, `[nginx-1.20.1](http://nginx.org/download/nginx-1.20.1.tar.gz)` has the same issue? If official nginx has the same issue, I think its better to report this issue to [nginx](https://trac.nginx.org/nginx/).

**Comment by zhangp8x** [comment]
@anguslee 

Thank you for your support, will follow your PR.

**Comment by zhangp8x** [comment]
@anguslee 

Thank you for your support, will follow your PR.

**Comment by zhangp8x** [comment]
@anguslee

Thank you for your contribution, need to provide signoffby first.

Could you please update the pull request commit message with "Signed-off-by:" in the following format
Signed-off-by: Name

Note: You are required to use your real name in the sign-off message.

**Comment by zhangp8x** [comment]
@anguslee 
Thank you for your effort, we will fix this issue in next release in another way.
Your change is rejected for side effect.

**Comment by daweiq** [comment]
@anguslee  The following patch should fix the issue.
https://github.com/intel/asynch_mode_nginx/commit/796c2734e0e8b53efd3c5655b60dd2794fcb992f
