### ISSUE TITLE
Unable to load module

### ISSUE THREAD

**Issue by cody0704** [intel/asynch_mode_nginx#50]
* OS: Redhat 8.4
  * Kernel: 4.18.0-305.12.1.el8_4.x86_64
  * openssl: OpenSSL 1.1.1g FIPS  21 Apr 2020 (Redhat Default)
* QAT Hardware: Intel QAT 8970
  * QAT Engine: v0.6.7
  * QAT Driver: qat1.7.l.4.14.0-00031
* Nginx: v1.20.1

Redhat cannot be installed from the source code, but because the default is already 1.1.1g, there is no need to update openssl

## OpenSSL

Confirm that openssl can use QAT

```bash
$ openssl speed rsa2048 
$ openssl speed -engine qatengine rsa2048
$ openssl speed -engine qatengine -async_jobs 8 rsa2048
```

|||sign|verify|sign/s|verify/s|
|---|---|---|---|---|---|
|cpu|rsa 2048 bits|0.000637s|0.000029s|1570.4|34797.8|
|openssl 1.1.1g qat sync|rsa 2048 bits|0.0000495s|0.000096s|2018.4|10426.2|
|openssl 1.1.1g qat async|rsa 2048 bits|0.000055s|0.000009s|18213.1|116548.2|

### Install

asynch_mode_nginx needs to specify the location of openssl lib, but I don’t know

```bash
$ ./configure --prefix=/etc/nginx --conf-path=/etc/nginx/nginx.conf \
--without-http_rewrite_module --with-http_ssl_module --with-http_stub_status_module \
--with-http_v2_module --with-stream --with-stream_ssl_module \
--add-dynamic-module=modules/nginx_qat_module/ \
--with-cc-opt="-DNGX_SECURE_MEM -I/opt/QAT/quickassist/include -I/opt/QAT/quickassist/include/dc 
-Wno-error=deprecated-declarations"
```

Check module

```bash
$ ll /etc/nginx/modules/
-rwxr-xr-x 1 root root 88096 Sep  6 06:40 ngx_ssl_engine_qat_module.so
```

### Config

```
load_module modules/ngx_ssl_engine_qat_module.so;
ssl_engine {
    use_engine qatengine;
    default_algorithms RSA,EC,DH,PKEY_CRYPTO;
    qat_engine {
            qat_offload_mode async;
            qat_notify_mode poll;
            qat_poll_mode heuristic;
            qat_sw_fallback on;
    }
}
```

### Nginx config test

```bash
$ /etc/nginx/sbin/nginx -t

nginx: [emerg] dlopen() "/usr/lib/nginx/modules/ngx_stream_module.so" failed (/usr/lib/nginx/modules/ngx_stream_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/conf/nginx.conf:12
nginx: configuration file /etc/nginx/conf/nginx.conf test failed
```

Does the installation method need to be modified?

**Comment by cody0704** [comment]
Reinstallation is normal
thank you all

**Comment by zhangp8x** [comment]
@cody0704 

Any questions, please feel free to contact us.

BRs
