### ISSUE TITLE
any plan on adaption for the nginx quic branch

### ISSUE THREAD

**Issue by zhuizhuhaomeng** [intel/asynch_mode_nginx#51]
quic has become more and more popular.
does intel has any plan on adaption the nginx quic branch?

**Comment by daweiq** [comment]
For the async-Nginx project,  we target to enable async support on latest LTS version of Nginx -- 1.20.1 at this moment. 
As we known, the nginx-quic branch is still in development stage and subject to rapid update.
We don't plan to release async support for nginx-quic now but we will keep tracking it.

**Comment by zhuizhuhaomeng** [comment]
nginx is now updated to 1.21.4. And the quic branch is also synced to 1.21.4
So if anynch_mode_nginx can sync to 1.21.4, it can be better to port to quic branch.
