### ISSUE TITLE
What does "External polling and heuristic polling are unavailable in SSL proxy and stream module" mean?

### ISSUE THREAD

**Issue by addzerotian** [intel/asynch_mode_nginx#54]
`Note: External polling and heuristic polling are unavailable in SSL proxy and stream module up to current release.`

What does this mean in README.md? I can set proxy_ssl_asynch on and qat_poll_mode heuristic, the nginx works well and the firmware requests/responses count has effective increase in qat fw_counters, have no idea about this comment.

**Comment by ShuaiYuan21** [comment]
This is a known issue in async-nginx reverse proxy mode when using secure upstream. Find more detail in #38
