### ISSUE TITLE
building async nginx with opentracing on

### ISSUE THREAD

**Issue by manjeetbhati** [intel/asynch_mode_nginx#57]
Hi,

I tried loading load_module modules/ngx_http_opentracing_module.so; by downloading .so file from opentracing git,
it returns binary incompatible, how do I build aysnc nginx with opentracing on?

error trace
nginx: [emerg] module "/var/www/modules/ngx_http_opentracing_module.so" is not binary compatible in /usr/share/nginx/conf/nginx.conf:2

**Comment by ShuaiYuan21** [comment]
Hi @manjeetbhati, could you follow the build instruction provided on https://github.com/opentracing-contrib/nginx-opentracing and try again?

**Comment by ShuaiYuan21** [comment]
No response from user for a long time, close this ticket.
