### ISSUE TITLE
issue seen with dasync engine

### ISSUE THREAD

**Issue by Kaustubh2455** [intel/asynch_mode_nginx#58]
Hi,
I wanted to use the dasync engine provided by OpenSSL. I have been able to load that engine and attach it to OpenSSL. I am using OpenSSL 1.1.1l and the async_mode_nginx repository. I have ssl_async on the Nginx config and I can see the requests getting offloaded. The issue I have been seeing is that some of the requests fail when I have more than one connection and multiple requests. The requests start to fail with as low as 3 requests with one thread and two connections.
Has anyone tried to test the dasync code with Nginx async? If yes was it scalable?

The error I get 
2022/08/17 03:11:10 [info] 15355#15355: *11784 SSL_do_handshake() failed (SSL: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac) while SSL handshaking, client: 10.0.1.1, server: 0.0.0.0:443

**Comment by Kaustubh2455** [comment]
@WalterRan attached the config.
[nginx_async_conf.txt](https://github.com/intel/asynch_mode_nginx/files/9392181/nginx_async_conf.txt)

**Comment by WalterRan** [comment]
As I know the dasync engine only implements the interface and does not implement the function, so I don't quite understand what is the purpose of this test.

**Comment by Kaustubh2455** [comment]
@WalterRan dasync engine does implement the function in SW for some ciphers.
I was doing this experiment because when working with the qat engine, I observed a similar issue. And as the dasync engine provides a similar interface, I wanted to confirm if it's an issue with Nginx or qat or if I am doing something wrong.
I use the sample Nginx-QAT config to run the qat engine with Nginx and see a similar issue.

**Comment by ShuaiYuan21** [comment]
Currently we fully support [qateengine](https://github.com/intel/QAT_Engine/), for other hardware engines, we cannot guarantee full support. But the implementation of other engines can refer to qateengine.
