### ISSUE TITLE
The file cannot be decompressed after being compressed by qatzip_filter

### ISSUE THREAD

**Issue by weeweetan** [intel/asynch_mode_nginx#59]
#### configure
qatzip_chunk_size 64k;
qatzip_stream_size 256k;
qatzip_buffers 16 8k;
#### file
low compression ratios, such as scans and size > 256k

**Comment by daweiq** [comment]
@weeweetan  Thanks for raising this.
It seems to be the same [#65](https://github.com/intel/QATzip/issues/65) issue raised in QATzip
So, we will track it in QATzip repo and close this one.

**Comment by weeweetan** [comment]
These are two different issues，this issue will cause the size of the downloaded file via qatzip_filter module smaller than without qatzip_filter module

**Comment by daweiq** [comment]
Is that because of the file being compressed by QATzip?

**Comment by weeweetan** [comment]
QATzip output data is ok，I think it should be the problem of qatzip_filter module
