### ISSUE TITLE
openresty make error

### ISSUE THREAD

**Issue by AlphaSRE** [intel/asynch_mode_nginx#7]
use openresty to make have error happened：
modules/nginx_qat_module/ngx_ssl_engine_qat_module.c:42:28: error: ngx_ssl_engine.h: No such file or directory
modules/nginx_qat_module/ngx_ssl_engine_qat_module.c:148: error: ‘NGX_SSL_ENGINE_CONF’ undeclared here (not in a function)
modules/nginx_qat_module/ngx_ssl_engine_qat_module.c:155: error: ‘NGX_SSL_ENGINE_SUB_CONF’ undeclared here (not in a function)

**Comment by AlphaSRE** [comment]
nginx 1.12.2 and 1.14.0 have error:
modules/nginx_qat_module//ngx_ssl_engine_qat_module.c:40:
src/event/ngx_event_openssl.h:143: error: expected ‘)’ before ‘*’ token
src/event/ngx_event_openssl.h:144: error: expected declaration specifiers or ‘...’ before ‘ngx_ssl_t’
src/event/ngx_event_openssl.h:146: error: expected declaration specifiers or ‘...’ before ‘ngx_ssl_t’
src/event/ngx_event_openssl.h:148: error: expected declaration specifiers or ‘...’ before ‘ngx_ssl_t’
src/event/ngx_event_openssl.h:150: error: expected declaration specifiers or ‘...’ before ‘ngx_ssl_t’
src/event/ngx_event_openssl.h:152: error: expected declaration specifiers or ‘...’ before ‘ngx_ssl_t’
src/event/ngx_event_openssl.h:154: error: expected declaration specifiers or ‘...’ before ‘ngx_ssl_t’
src/event/ngx_event_openssl.h:155: error: expected declaration specifiers or ‘...’ before ‘ngx_ssl_t’
src/event/ngx_event_openssl.h:157: error: expected declaration specifiers or ‘...’ before ‘ngx_ssl_t’
src/event/ngx_event_openssl.h:162: error: expected declaration specifiers or ‘...’ before ‘ngx_ssl_t’
src/event/ngx_event_openssl.h:163: error: expected declaration specifiers or ‘...’ before ‘ngx_ssl_t’
src/event/ngx_event_openssl.h:164: error: expected ‘)’ before ‘*’ token
src/event/ngx_event_openssl.h:166: error: expected declaration specifiers or ‘...’ before ‘ngx_ssl_t’
src/event/ngx_event_openssl.h:169: error: expected ‘)’ before ‘*’ token

**Comment by AlphaSRE** [comment]
openssl version OpenSSL 1.1.0c  10 Nov 2016

**Comment by daweiq** [comment]
@AlphaSRE current async-Nginx are based on Nginx-1.10.3 and we are planning on move to Nginx-1.14. 
Before the that, you can apply the async-Nginx patch to 1.14 . 
Here's the link for your reference. 
https://github.com/intel/asynch_mode_nginx/issues/4

**Comment by daweiq** [comment]
@AlphaSRE If no more comments, I will close this issue tomorrow.

**Comment by AlphaSRE** [comment]
> @AlphaSRE If no more comments, I will close this issue tomorrow.

Thanks. When the patch publish

**Comment by daweiq** [comment]
We plan to rebase to Nginx-1.14 on Q1/Q2 release next year.
