### ISSUE TITLE
SSL_do_handshake() failed when nginx worker_processes gt SHIM NumProcesses

### ISSUE THREAD

**Issue by Yuanbo-2019** [intel/asynch_mode_nginx#83]
env:
|||
|---|---|
|cpu|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz|
|nginx	| asynch_mode_nginx-master
|openssl	| OpenSSL 1.1.1f  31 Mar 2020
|QAT Engine	| QAT_Engine-master
|QAT driver	| QAT.L.4.26.0-00008 1.7
|QAT 	| Intel® QuickAssist Adapter 8970

refer 
https://www.intel.cn/content/www/cn/zh/developer/articles/guide/nginx-https-with-qat-tuning-guide.html?wapkw=qat
to test

question:
worker_processes set 32 in nginx.conf
NumProcesses set 16 in c6xx_dev0.conf

./wrk -t 24 -c 1000 -d 5S https://127.0.0.1

Running 5s test @ https://127.0.0.1
  24 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.72ms    1.05ms  27.54ms   91.51%
    Req/Sec   380.41    103.33     0.92k    70.32%
  46162 requests in 5.10s, 37.86MB read
  Socket errors: connect 42136, read 0, write 0, timeout 0
Requests/sec:   9051.54
Transfer/sec:      7.42MB

![Uploading 企业微信截图_17272541529551.png…]()

modify nginx.conf  to test tls1.3 ecdhe-x25519-rsa2k
```
ssl_protocols TLSv1.3;
ssl_ciphers AES128-SHA;
ssl_ecdh_curve X25519:secp384r1;
```

nginx error.log print:
[error] ADF_UIO_PROXY: icp_adf_userProcessToStart: Failed to start SHIM
QAT HW initialization Failed.
2024/09/25 16:28:12 [crit] 537623#537623: *80258 SSL_do_handshake() failed (SSL: error:800B30C3:lib(128):qat_hw_init:icp sal userstart fail error:800C2044:lib(128):qat_pkey_ecx_keygen:internal error error:141C8041:SSL routines:tls_construct_stoc_key_share:malloc failure) while SSL handshaking, client: 127.0.0.1, server: 0.0.0.0:443

![企业微信截图_17272541165269](https://github.com/user-attachments/assets/c145a0a3-ecb1-4e78-898c-89ae60a0aadd)

modify nginx.conf  to test tls1.2 rsa2k
```
ssl_protocols TLSv1.2;
ssl_ciphers AES128-SHA;
# ssl_ecdh_curve X25519:secp384r1;
```

nginx error.log print:
[error] ADF_UIO_PROXY: icp_adf_userProcessToStart: Failed to start SHIM
QAT HW initialization Failed.
2024/09/26 10:56:18 [crit] 653837#653837: *43708 SSL_do_handshake() failed (SSL: error:800B10C7:lib(128):qat_hw_init:icp sal userstart fail error:800C6044:lib(128):qat_rsa_priv_dec:internal error error:1419F093:SSL routines:tls_process_cke_rsa:decryption failed) while SSL handshaking, client: 127.0.0.1, server: 0.0.0.0:443
![企业微信截图_17273197357265](https://github.com/user-attachments/assets/3c0f4c83-09a6-4f82-be2b-b348cd909497)

**Comment by hardikpatel9** [comment]
Hi @Yuanbo-2019,
Could the reason be that the driver configuration/or relevant cannot load properly and the QAT hardware initialization fails? The driver configuration files should be at /path/to/qat_engine/qat/config. Could you please cross-verify by loading the correct required options as per your needs into the shim/driver configuration file and copy it into /etc, then try to restart the service using adf_ctl restart? If you are still facing the issue, can you please attach both the nginx.conf and the driver configuration file here? Based on that, can help further.

**Comment by Yuanbo-2019** [comment]
/etc/c6xx_dev0.conf
```
[GENERAL]
ServicesEnabled = cy

# Set the service profile to determine available features
# =====================================================================
#                               DEFAULT    CRYPTO  COMPRESSION  CUSTOM1
# Asymmetric Crypto                *         *                     *
# Symmetric Crypto                 *         *                     *
# Hash                             *         *          *          *
# Cipher                           *         *                     *
# MGF KeyGen                       *         *
# SSL/TLS KeyGen                   *         *                     *
# HKDF                                       *                     *
# Compression                      *                    *          *
# Decompression (stateless)        *                    *          *
# Decompression (stateful)         *                    *
# Service Chaining                                      *
# Device Utilization                         *          *          *
# Rate Limiting                              *          *          *
# =====================================================================
ServicesProfile = DEFAULT

ConfigVersion = 2

#Default values for number of concurrent requests*/
CyNumConcurrentSymRequests = 512
CyNumConcurrentAsymRequests = 64

#Statistics, valid values: 1,0
statsGeneral = 1
statsDh = 1
statsDrbg = 1
statsDsa = 1
statsEcc = 1
statsKeyGen = 1
statsDc = 1
statsLn = 1
statsPrime = 1
statsRsa = 1
statsSym = 1


# Specify size of intermediate buffers for which to
# allocate on-chip buffers. Legal values are 32 and
# 64 (default is 64). Specify 32 to optimize for
# compressing buffers <=32KB in size.
DcIntermediateBufferSizeInKB = 64

# This flag is to enable device auto reset on heartbeat error
AutoResetOnError = 0

##############################################
# Kernel Instances Section
##############################################
[KERNEL]
NumberCyInstances = 0
NumberDcInstances = 0

##############################################
# User Process Instance Section
##############################################
[SHIM]
NumberCyInstances = 1
NumberDcInstances = 0
NumProcesses = 16
LimitDevAccess = 1

# Crypto - User instance #0
Cy0Name = "UserCY0"
Cy0IsPolled = 1
# List of core affinities
Cy0CoreAffinity = 0

```

nginx.conf
```
user root; 
worker_processes 24;
Worker_rlimit_nofile 100000;
load_module modules/ngx_ssl_engine_qat_module.so;
events {
use epoll;
worker_connections 10240;
multi_accept on;
accept_mutex on;
}

ssl_engine {
use_engine qatengine;
default_algorithms ALL;
qat_engine {
qat_offload_mode async;
qat_notify_mode poll;
qat_poll_mode heuristic;
qat_shutting_down_release off;
 }

}
http {
server {
listen example:443 ssl reuseport backlog=131072 so_keepalive=off rcvbuf=65536 sndbuf=65536;
keepalive_timeout 0s;
ssl_verify_client off;
ssl_session_tickets off;
ssl_session_cache off;
access_log off;
ssl_asynch on;
ssl_session_timeout 300s;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ecdh_curve x25519;
#ssl_ciphers AES128-SHA;
#ssl_prefer_server_ciphers on;
ssl_certificate server2048.crt;
ssl_certificate_key server2048.key;
location / {
root html;
index index.html index.htm;
  }
 }
}
```

The configuration file above has issues，but when **worker_processes** lt **NumProcesses** , everything is ok。so I continue with the testing。

I encountered another issue，and here are some test data。when nginx worker_processes >= 4， Performance drop，What could be the possible reasons?"

| nginx worker_processes | cps |
|-|-|
|1|5k|
|2|10k|
|3|15K|
|4|17K|
|8|17K|

**Comment by hardikpatel9** [comment]
Hi @Yuanbo-2019 ,

To enhance performance and achieve load balancing across Intel QAT accelerators, the process affinity option should be disabled by setting LimitDevAccess = 0. This configuration allows user space processes to utilize available logical instances from all Intel QAT devices, thereby optimizing resource usage and improving overall efficiency. Setting LimitDevAccess = 0 means that processes in this section can access multiple Intel QAT endpoints.

**Comment by Yuanbo-2019** [comment]
thank you very much@hardikpatel9 . After setting LimitDevAccess = 0 in all three device config file, user space processes can exactly access all three Intel QAT endpoints, and now I have the peak performance when **worker_processes** is set to 12. here are new test data
|nginx worker_processes|cps|
|-|-|
|4|17k|
|8|33k|
|12|52k|
|16|53k|
|23|54k|

![图片](https://github.com/user-attachments/assets/2ca971a6-10ce-427e-82e1-3ab29d7c0506)
According to the figure above from <intel-quickassist-technology-nginx-performance-white-paper>, 12C achieves peak performance。
Is it possible to access only 4 processes on one qat endpoint ?
